title: <p align="center"> Said Taghadouini </p>

logo: "images/photo.jpeg?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/taghadouinisaid/">LinkedIn</a> |
  <a href="https://github.com/staghado">GitHub</a>
  </p>
  
  <p align="justify">
  I am Data Scientist focusing mainly on Deep Learning and Computer Vision specifically.
  <br><br>
  I have a Masters degree in Mathematics/Computer Science and Machine Learning
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
