baseURL = "https://staghado.github.io/"  
languageCode = "en-us" 
title = "Said's ML Diary – Decoding the Future, One Algorithm at a Time"  
theme = "PaperMod" 

[params]
  author = "Said Taghadouini"
  description = "A curated list of subjects of interest to me."