name: Deploy Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Environment
      run: sudo apt-get install -y rsync

    - name: Synchronize Directories
      run: |
        rsync -vuar --ignore-existing public/ .